spring:
  application:
    name: ai-server
  profiles:
    active: local
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
      - optional:nacos:common-datasource.yaml
      - optional:nacos:common-server.yaml
server:
  port: 49094
